export const WORKFLOW_RUNTIME_LITE_VERSION = 1 as const;
export const WORKFLOW_RUNTIME_MAX_RUNS = 10;
export const WORKFLOW_RUNTIME_MAX_PACKET_DISPLAY_CHARS = 4000;
export const WORKFLOW_RUNTIME_MAX_METADATA_STRING_CHARS = 500;
