export const BACKEND_ERROR_DOMAINS = [
  "AUTH",
  "WORKSPACE",
  "PERMISSION",
  "VALIDATION",
  "IDEMPOTENCY",
  "SYNC",
  "AGENT",
  "PROVIDER",
  "TOOL",
  "ARTIFACT",
  "OBSERVABILITY",
  "DEPLOYMENT",
  "HISTORY",
  "INTERNAL",
] as const;

export type BackendErrorDomain = (typeof BACKEND_ERROR_DOMAINS)[number];

export const BackendErrorCodes = {
  AUTH_UNAUTHENTICATED: "AUTH_UNAUTHENTICATED",
  AUTH_REQUIRED: "AUTH_REQUIRED",
  AUTH_SESSION_EXPIRED: "AUTH_SESSION_EXPIRED",
  AUTH_INVALID_CREDENTIAL: "AUTH_INVALID_CREDENTIAL",

  WORKSPACE_NOT_FOUND: "WORKSPACE_NOT_FOUND",
  WORKSPACE_ACCESS_DENIED: "WORKSPACE_ACCESS_DENIED",
  WORKSPACE_LIMIT_EXCEEDED: "WORKSPACE_LIMIT_EXCEEDED",
  WORKSPACE_STATE_NOT_FOUND: "WORKSPACE_STATE_NOT_FOUND",
  WORKSPACE_STATE_CONFLICT: "WORKSPACE_STATE_CONFLICT",
  WORKSPACE_STATE_SECRET_DETECTED: "WORKSPACE_STATE_SECRET_DETECTED",
  WORKSPACE_STATE_SCHEMA_MISMATCH: "WORKSPACE_STATE_SCHEMA_MISMATCH",
  WORKSPACE_STATE_INVALID_REGISTRY_REFERENCE:
    "WORKSPACE_STATE_INVALID_REGISTRY_REFERENCE",
  WORKSPACE_SNAPSHOT_TOO_LARGE: "WORKSPACE_SNAPSHOT_TOO_LARGE",
  WORKSPACE_HYDRATION_CONFLICT: "WORKSPACE_HYDRATION_CONFLICT",
  WORKSPACE_HYDRATION_FAILED: "WORKSPACE_HYDRATION_FAILED",

  PERMISSION_DENIED: "PERMISSION_DENIED",
  PERMISSION_SCOPE_MISSING: "PERMISSION_SCOPE_MISSING",
  PERMISSION_RISK_REJECTED: "PERMISSION_RISK_REJECTED",

  VALIDATION_FAILED: "VALIDATION_FAILED",
  VALIDATION_INVALID_ID: "VALIDATION_INVALID_ID",
  VALIDATION_SCHEMA_MISMATCH: "VALIDATION_SCHEMA_MISMATCH",

  IDEMPOTENCY_KEY_MISSING: "IDEMPOTENCY_KEY_MISSING",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
  IDEMPOTENCY_PENDING: "IDEMPOTENCY_PENDING",
  IDEMPOTENCY_EXPIRED: "IDEMPOTENCY_EXPIRED",
  IDEMPOTENCY_KEY_CONFLICT: "IDEMPOTENCY_KEY_CONFLICT",
  IDEMPOTENCY_REPLAY_UNAVAILABLE: "IDEMPOTENCY_REPLAY_UNAVAILABLE",

  SYNC_CONFLICT: "SYNC_CONFLICT",
  SYNC_STALE_CURSOR: "SYNC_STALE_CURSOR",
  SYNC_BACKEND_UNAVAILABLE: "SYNC_BACKEND_UNAVAILABLE",
  SYNC_DOMAIN_NOT_SUPPORTED: "SYNC_DOMAIN_NOT_SUPPORTED",
  SYNC_PAYLOAD_TOO_LARGE: "SYNC_PAYLOAD_TOO_LARGE",
  SYNC_OPERATION_CONFLICT: "SYNC_OPERATION_CONFLICT",
  SYNC_OPERATION_NOT_FOUND: "SYNC_OPERATION_NOT_FOUND",
  SYNC_OPERATION_NOT_RETRYABLE: "SYNC_OPERATION_NOT_RETRYABLE",
  SYNC_OPERATION_NOT_CANCELLABLE: "SYNC_OPERATION_NOT_CANCELLABLE",
  SYNC_SECRET_DETECTED: "SYNC_SECRET_DETECTED",

  AGENT_NOT_FOUND: "AGENT_NOT_FOUND",
  AGENT_RUNTIME_UNAVAILABLE: "AGENT_RUNTIME_UNAVAILABLE",
  AGENT_TASK_REJECTED: "AGENT_TASK_REJECTED",
  AGENT_TASK_NOT_FOUND: "AGENT_TASK_NOT_FOUND",

  PROVIDER_NOT_CONFIGURED: "PROVIDER_NOT_CONFIGURED",
  PROVIDER_TIMEOUT: "PROVIDER_TIMEOUT",
  PROVIDER_REQUEST_FAILED: "PROVIDER_REQUEST_FAILED",
  PROVIDER_RATE_LIMITED: "PROVIDER_RATE_LIMITED",

  TOOL_NOT_FOUND: "TOOL_NOT_FOUND",
  TOOL_INPUT_INVALID: "TOOL_INPUT_INVALID",
  TOOL_SECRET_DETECTED: "TOOL_SECRET_DETECTED",
  TOOL_PERMISSION_DISABLED: "TOOL_PERMISSION_DISABLED",
  TOOL_RUN_FAILED: "TOOL_RUN_FAILED",
  TOOL_RUN_NOT_FOUND: "TOOL_RUN_NOT_FOUND",
  TOOL_RUN_NOT_CONFIRMABLE: "TOOL_RUN_NOT_CONFIRMABLE",
  TOOL_CONFIRMATION_EXPIRED: "TOOL_CONFIRMATION_EXPIRED",
  TOOL_PERMISSION_DENIED: "TOOL_PERMISSION_DENIED",
  TOOL_MATERIALIZATION_NOT_AVAILABLE: "TOOL_MATERIALIZATION_NOT_AVAILABLE",

  ARTIFACT_NOT_FOUND: "ARTIFACT_NOT_FOUND",
  ARTIFACT_WRITE_FAILED: "ARTIFACT_WRITE_FAILED",
  ARTIFACT_REDACTION_REQUIRED: "ARTIFACT_REDACTION_REQUIRED",
  ARTIFACT_SECRET_DETECTED: "ARTIFACT_SECRET_DETECTED",
  ARTIFACT_CONTENT_TOO_LARGE: "ARTIFACT_CONTENT_TOO_LARGE",
  ARTIFACT_REFERENCE_INVALID: "ARTIFACT_REFERENCE_INVALID",
  ARTIFACT_REFERENCE_CONFLICT: "ARTIFACT_REFERENCE_CONFLICT",

  OBSERVABILITY_EVENT_REJECTED: "OBSERVABILITY_EVENT_REJECTED",
  OBSERVABILITY_TRACE_MISSING: "OBSERVABILITY_TRACE_MISSING",
  OBSERVABILITY_EXPORT_FAILED: "OBSERVABILITY_EXPORT_FAILED",

  DEPLOYMENT_NOT_FOUND: "DEPLOYMENT_NOT_FOUND",
  DEPLOYMENT_ROLLOUT_FAILED: "DEPLOYMENT_ROLLOUT_FAILED",
  DEPLOYMENT_ENV_INVALID: "DEPLOYMENT_ENV_INVALID",

  HISTORY_NOT_FOUND: "HISTORY_NOT_FOUND",
  HISTORY_CURSOR_INVALID: "HISTORY_CURSOR_INVALID",
  HISTORY_CURSOR_EXPIRED: "HISTORY_CURSOR_EXPIRED",
  HISTORY_MEMORY_TOO_LARGE: "HISTORY_MEMORY_TOO_LARGE",
  HISTORY_RETENTION_EXCEEDED: "HISTORY_RETENTION_EXCEEDED",

  INTERNAL_UNEXPECTED: "INTERNAL_UNEXPECTED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INTERNAL_NOT_IMPLEMENTED: "INTERNAL_NOT_IMPLEMENTED",
  INTERNAL_DEPENDENCY_FAILED: "INTERNAL_DEPENDENCY_FAILED",
} as const;

export type KnownBackendErrorCode =
  (typeof BackendErrorCodes)[keyof typeof BackendErrorCodes];

export type BackendErrorCode =
  | KnownBackendErrorCode
  | `${BackendErrorDomain}_${Uppercase<string>}`;

const backendErrorDomainPattern = new RegExp(
  `^(${BACKEND_ERROR_DOMAINS.join("|")})_[A-Z0-9]+(?:_[A-Z0-9]+)*$`,
);

export function isBackendErrorCode(value: string): value is BackendErrorCode {
  return backendErrorDomainPattern.test(value);
}
